### ISSUE TITLE
Estimate hours needed to complete

### ISSUE THREAD

**Issue by Jdkol3s** [Alooishus/ci_recipe_book#3]
What is a road map or list of everything you would need to complete and launch?

**Comment by Alooishus** [comment]
I was gonna sit down next time and write that out a bit.  I’ll let you know when it’s done

**Comment by Jdkol3s** [comment]
Sounds good... Let me know if I can be involved. Probably a lot of learning on my part

**Comment by Alooishus** [comment]
I think that would be awesome and I would love for anyone interested to get involved.  
I’ll try and keep the live site up to date with this code base so people can mess around and request features or notify of bugs and whatnot.

**Comment by Alooishus** [comment]
I can easily talk you through a local environment setup as well if you want the code to mess around with!
